// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.30;

import {Script} from "forge-std/Script.sol";
import {LibClone} from "solady/utils/LibClone.sol";
import {Chains} from "./Chains.sol";

/// @notice Writes `fixtures/address-vectors.json`: per chain, the instance's
/// CREATE2 init code hash and address (keyless deployer, salt 0) and the
/// deposit addresses of fixed recipients, for a TypeScript implementation to
/// be checked against. No broadcast, no RPC; `test/Forwarder.t.sol` fails if
/// the file is stale. Format afterwards with prettier.
contract WriteAddressVectors is Script {
    function recipients() public pure returns (bytes32[6] memory) {
        return [
            bytes32(0x0000000000000000000000000000000000000000000000000000000000000001),
            bytes32(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff),
            bytes32(0x00000000000000000000000000000000000000000000000000000000deadbeef),
            bytes32(0xdeadbeef00000000000000000000000000000000000000000000000000000000),
            bytes32(0x7a1d4e3b9c5f60718293a4b5c6d7e8f9012a3b4c5d6e7f8091a2b3c4d5e6f708),
            keccak256("miso:test-recipient")
        ];
    }

    function cloneOf(address instance, bytes32 r) public pure returns (address) {
        return LibClone.predictDeterministicAddress(instance, abi.encodePacked(r), r, instance);
    }

    function run() external {
        Chains.Chain[2] memory cs = Chains.all();
        string memory chainsJson;
        for (uint256 i; i < cs.length; i++) {
            chainsJson = string.concat(chainsJson, i == 0 ? "" : ",", _chainJson(cs[i]));
        }
        vm.writeFile(
            "fixtures/address-vectors.json",
            string.concat(
                '{"note":"Generated by script/WriteAddressVectors.s.sol. Do not edit by hand.","create2Deployer":"',
                vm.toString(Chains.CREATE2_DEPLOYER),
                '","salt":"',
                vm.toString(Chains.SALT),
                '","chains":{',
                chainsJson,
                "}}\n"
            )
        );
    }

    function _chainJson(Chains.Chain memory c) internal pure returns (string memory) {
        bytes32 hash = keccak256(Chains.initCode(c));
        address instance = vm.computeCreate2Address(Chains.SALT, hash, Chains.CREATE2_DEPLOYER);
        bytes32[6] memory rs = recipients();
        string memory vectors;
        for (uint256 i; i < rs.length; i++) {
            vectors = string.concat(
                vectors,
                i == 0 ? "" : ",",
                '{"recipient":"',
                vm.toString(rs[i]),
                '","address":"',
                vm.toString(cloneOf(instance, rs[i])),
                '"}'
            );
        }
        return string.concat(
            '"',
            c.name,
            '":{"chainId":',
            vm.toString(c.chainId),
            ',"usdc":"',
            vm.toString(c.usdc),
            '","messenger":"',
            vm.toString(c.tokenMessenger),
            '","initCodeHash":"',
            vm.toString(hash),
            '","factory":"',
            vm.toString(instance),
            '","vectors":[',
            vectors,
            "]}"
        );
    }
}
